#!/usr/bin/env bash
# Daily workspace cleanup scan — generates a suggested deletions report.
# No Claude/API calls. Phase 3 (deletion) is done manually via Claude.

WORKSPACE="/Users/danieldanut/Agentic Workspace"
OUTPUT_DIR="$WORKSPACE/Youtube/Quick Access/Suggested Deletion"
DATE=$(date +%Y-%m-%d)
REPORT="$OUTPUT_DIR/.suggested_deletions_${DATE}.md"

mkdir -p "$OUTPUT_DIR"
> "$REPORT"

# ── helpers ────────────────────────────────────────────────────────────────────

du_size() { du -sh "$1" 2>/dev/null | cut -f1; }
a() { printf '%s\n' "$@" >> "$REPORT"; }

SAFE_TOTAL=0
REVIEW_TOTAL=0

# Write a section table from a list of NUL-separated paths.
# Usage: write_section "Header" "Reason text" paths...
write_section() {
  local header="$1" reason="$2"; shift 2
  local count=0
  local rows=()
  for p in "$@"; do
    [[ -e "$p" ]] || continue
    rows+=("| \`${p}\` | $(du_size "$p") | ${reason} |")
    (( count++ ))
  done
  if (( count > 0 )); then
    a "### ${header}"
    a "| Path | Size | Reason |"
    a "|------|------|--------|"
    for r in "${rows[@]}"; do a "$r"; done
    a ""
  fi
  echo "$count"
}

# ── scan helpers ───────────────────────────────────────────────────────────────

find_files() { find "$WORKSPACE" "$@" -not -path "*/.git/*" 2>/dev/null; }
find_no_nm() { find "$WORKSPACE" "$@" -not -path "*/.git/*" -not -path "*/node_modules/*" 2>/dev/null; }

# ── build candidate arrays ─────────────────────────────────────────────────────

mapfile -t pyc_dirs  < <(find_no_nm -name "__pycache__" -type d)
mapfile -t pyc_files < <(find_no_nm \( -name "*.pyc" -o -name "*.pyo" \) -type f)
mapfile -t ds_store  < <(find_files -name ".DS_Store" -type f)
mapfile -t log_files < <(find_files -name "*.log" -type f)
mapfile -t build_art < <(find_no_nm \( -name "*.egg-info" -o -name "dist" -o -name "build" \) -print)

# Empty project stubs
empty_stubs=()
while IFS= read -r d; do
  [[ -n "$(find "$d" -mindepth 1 -not -type d 2>/dev/null | head -1)" ]] || empty_stubs+=("$d")
done < <(find "$WORKSPACE/Youtube/Output" -mindepth 2 -maxdepth 2 -type d 2>/dev/null)

# Review — tool deps
mapfile -t tool_deps < <(find_files \( -name "node_modules" -o -name "venv" -o -name ".venv" \) -type d)

# Review — model files
mapfile -t model_dirs  < <(find_files -name "whisper_models" -type d)
mapfile -t model_files < <(find_files \( -name "*.pt" -o -name "*.bin" -o -name "*.onnx" -o -name "*.safetensors" \) -type f)

# Review — orphaned drafts (outside Youtube/Input/)
orphan_drafts=()
while IFS= read -r f; do
  [[ "$f" != *"/Youtube/Input/"* ]] && orphan_drafts+=("$f")
done < <(find_files -name "*_draft*.md" -type f 2>/dev/null)

# ── write report ───────────────────────────────────────────────────────────────

a "# Suggested Deletions — ${DATE}"
a ""
a "---"
a ""
a "## Safe to Delete"
a ""

n=$(write_section "Python Cache (__pycache__ dirs)" \
  "Compiled bytecode, regenerated automatically" "${pyc_dirs[@]}")
SAFE_TOTAL=$((SAFE_TOTAL + n))

n=$(write_section "Python Cache (.pyc / .pyo files)" \
  "Compiled bytecode, regenerated automatically" "${pyc_files[@]}")
SAFE_TOTAL=$((SAFE_TOTAL + n))

n=$(write_section "macOS Artifacts (.DS_Store)" \
  "System metadata, not needed" "${ds_store[@]}")
SAFE_TOTAL=$((SAFE_TOTAL + n))

n=$(write_section "Empty Project Stubs" \
  "Pre-created folder with no content" "${empty_stubs[@]}")
SAFE_TOTAL=$((SAFE_TOTAL + n))

n=$(write_section "Build Artifacts" \
  "Build output, regenerated by build step" "${build_art[@]}")
SAFE_TOTAL=$((SAFE_TOTAL + n))

n=$(write_section "Log Files" \
  "Log output" "${log_files[@]}")
SAFE_TOTAL=$((SAFE_TOTAL + n))

if (( SAFE_TOTAL == 0 )); then a "_No safe candidates found._"; a ""; fi

a "---"
a ""
a "## Review First"
a ""

n=$(write_section "Tool Dependencies (node_modules / venv)" \
  "Reinstallable via npm install / pip install" "${tool_deps[@]}")
REVIEW_TOTAL=$((REVIEW_TOTAL + n))

n=$(write_section "Large Model Files" \
  "Downloaded model weights, can be re-fetched" "${model_dirs[@]}" "${model_files[@]}")
REVIEW_TOTAL=$((REVIEW_TOTAL + n))

n=$(write_section "Orphaned Drafts" \
  "Draft file outside Input/ structure" "${orphan_drafts[@]}")
REVIEW_TOTAL=$((REVIEW_TOTAL + n))

if (( REVIEW_TOTAL == 0 )); then a "_No review candidates found._"; a ""; fi

TOTAL=$((SAFE_TOTAL + REVIEW_TOTAL))

# Prepend summary (insert after title line)
SUMMARY="
**Total candidates:** ${TOTAL} items  |  **Safe to delete:** ${SAFE_TOTAL}  |  **Review first:** ${REVIEW_TOTAL}
"
# Use a temp file to prepend summary after the title
TMP=$(mktemp)
head -2 "$REPORT" > "$TMP"
printf '%s\n' "$SUMMARY" >> "$TMP"
tail -n +3 "$REPORT" >> "$TMP"
mv "$TMP" "$REPORT"

echo "Scan complete — ${TOTAL} candidates (${SAFE_TOTAL} safe, ${REVIEW_TOTAL} review)."
echo "Report: $REPORT"
